version: "3.9"
services: 
    api-server:
        image: api-server
        restart: unless-stopped
        build: ./backend/
        networks: 
            - routek
        ports: 
            - "3001:3001"
    react-app:
        image: react-app
        restart: unless-stopped
        build: ./frontend/
        networks: 
            - routek
        environment:
            CHOKIDAR_USEPOLLING: "true"
        ports: 
            - "3000:3000"
        volumes: 
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
    python-api:
        image: python-api
        restart: unless-stopped
        build: ./python/
        networks: 
            - routek
        ports: 
            - "5000:5000"

networks:
    routek:
        driver: bridge