version: "3"
services: 
    api-server:
        image: api-server
        restart: unless-stopped
        build: ./backend/
        environment:
            CHOKIDAR_USEPOLLING: "true"
        ports: 
            - "3001:3001"
        networks: 
            - routek
        volumes: 
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
    react-app:
        image: react-app
        restart: unless-stopped
        build: ./frontend/
        environment:
            CHOKIDAR_USEPOLLING: "true"
        ports: 
            - "3000:3000"
        networks:
            - routek
        volumes: 
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
networks: 
    routek:
        driver: bridge